#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CS="$ROOT/patches/callSession.js"
BC="$ROOT/patches/brainClient.js"
CTRL="$ROOT/patches/control-server.js"
fail() { echo "assert-demo-runtime-patches: FAIL: $*" >&2; exit 1; }
[[ -f "$CS" ]] || fail "missing callSession patch"
grep -q "queueTtsSegment(segmentText, segmentId, handlingToken)" "$CS" || fail "missing queueTtsSegment method"
grep -q "this.queueTtsSegment(" "$CS" || fail "missing queueTtsSegment call"
grep -q "BRAIN_STREAMING_ENABLED && playbackDone" "$CS" || fail "missing streaming fallback speak shape"
grep -q "VERA_DEMO_SHOP_NORMALIZE_20260904" "$CS" || fail "missing normalize-then-write marker"
grep -q "normalizeDemoShopBooking" "$CS" || fail "missing normalizeDemoShopBooking"
grep -q "maybeDemoShopHangupBook" "$CS" || fail "missing hangup normalizer hook"
grep -q "VERA_DEMO_SHOP_TTS_PREP_20260904" "$CS" || fail "missing TTS speak-prep marker"
grep -q "normalizeDemoShopSpeakText" "$CS" || fail "missing normalizeDemoShopSpeakText"
grep -q "VERA_DEMO_SHOP_HARDEN_20260904" "$CS" || fail "missing Demo Shop harden marker"
grep -q "isDemoShopGoodbye" "$CS" || fail "missing goodbye guard"
grep -q "isDemoShopIncompleteContact" "$CS" || fail "missing incomplete contact guard"
grep -q "syncDemoShopContactMaxUtt" "$CS" || fail "missing contact max-utt sync"
grep -q "VERA_DEMO_SHOP_COLLECTPASS_20260907" "$CS" || fail "missing COLLECTPASS marker"
grep -q "booking_incomplete" "$CS" || fail "missing collect-pass booking_incomplete tune"
grep -q "VERA_DEMO_SHOP_PERSONEND_20260907" "$CS" || fail "missing PERSONEND marker on callSession"
grep -q "maybeRewriteDemoShopFakeConfirm" "$CS" || fail "missing fake-confirm rewrite"
grep -q "maybeDemoShopMidCallBook" "$CS" || fail "missing maybeDemoShopMidCallBook"
[[ -f "$BC" ]] || fail "missing brainClient patch"
grep -q "openai_direct_stream_error" "$BC" || fail "missing stream error log"
grep -q "err_message" "$BC" || fail "missing err_message serialize"
[[ -f "$CTRL" ]] || fail "missing control-server patch"
grep -q "Always fire workflow" "$CTRL" || fail "missing hangup always-fire"
grep -q "VERA_DEMO_SHOP_TURN_20260905" "$CS" || fail "missing Demo Shop turn marker"
grep -q "onBargeInDetected" "$CS" || fail "missing onBargeInDetected barge-in stop wire"
grep -q "stt_barge_in_stop_playback" "$CS" || fail "missing barge-in stop playback log"
grep -q "isDemoShopNonsenseTranscript" "$CS" || fail "missing nonsense STT gate"
grep -q "demo_shop_hangup_book_skip" "$CS" || fail "missing hangup book skip log"
grep -q "isDemoShopResolvedPtStart" "$CS" || fail "missing PT start resolver"
grep -q "truncateDemoShopReply" "$CS" || fail "missing reply truncate"
grep -q "maybeRewriteDemoShopInventedProduct" "$CS" || fail "missing invented product rewrite"
grep -q "VERA_DEMO_SHOP_PSTN_WAIT_20260905" "$CS" || fail "missing Demo Shop PSTN wait marker"
grep -q "waitDemoShopPstnSegmentAudioEnd" "$CS" || fail "missing PSTN segment audio wait"
grep -q "interruptDemoShopQueuedTts" "$CS" || fail "missing rewrite clear+stop interrupt"
grep -q "ttsSegmentChainEpoch" "$CS" || fail "missing TTS chain epoch guard"
grep -q "shouldAbortDemoShopStreamForRewrite" "$CS" || fail "missing mid-stream rewrite abort"
grep -q "demo_shop_pstn_segment_wait_done" "$CS" || fail "missing PSTN segment wait done log"
grep -q "demo_shop_tts_interrupt_for_rewrite" "$CS" || fail "missing rewrite interrupt log"
grep -q "demoShopMaxSegments" "$CS" || fail "missing Demo Shop segment cap"
grep -q "VERA_DEMO_SHOP_ONEWAV_20260905" "$CS" || fail "missing Demo Shop one-WAV marker"
grep -q "VERA_DEMO_SHOP_PSTN_WAIT_20260905" "$CS" || fail "missing PSTN_WAIT marker retention"
grep -q "VERA_DEMO_SHOP_TURN_20260905" "$CS" || fail "missing TURN marker retention"
# CONVOFEEL: Demo Shop PSTN streams first-audio; other PSTN stays ONEWAV.
# Old Nemotron-stream exception without PSTN_WAIT is still forbidden.
if grep -q "Demo Shop exception: stream Nemotron" "$CS"; then
  fail "legacy demo-shop PSTN streaming exception (no PSTN_WAIT) still present"
fi
grep -q "VERA_DEMO_SHOP_CONVOFEEL_20260906" "$CS" || fail "missing Demo Shop CONVOFEEL marker"
grep -q "demo_shop_streamtts_arm" "$CS" || fail "missing Demo Shop STREAMTTS arm log"
grep -q "demo_shop_first_audio_queued" "$CS" || fail "missing Demo Shop first-audio queued log"
grep -q "transport.mode === 'pstn' && this.tenantId !== 'demo-shop'" "$CS" || fail "missing Demo Shop STREAMTTS PSTN exemption (other tenants stay ONEWAV)"
grep -q "waitDemoShopPstnSegmentAudioEnd" "$CS" || fail "missing PSTN segment audio wait (overlap safety)"
grep -q "demoShopPstnPlayGeneration" "$CS" || fail "missing PSTN wait generation token"
grep -q "VERA_DEMO_SHOP_MUSTBOOK_20260905" "$CS" || fail "missing Demo Shop MUSTBOOK marker"
grep -q "maybeRewriteDemoShopHandoff" "$CS" || fail "missing Demo Shop handoff rewrite"
grep -q "isDemoShopHandoffSpeak" "$CS" || fail "missing Demo Shop handoff detector"
grep -q "demo_shop_handoff_rewritten" "$CS" || fail "missing Demo Shop handoff rewrite log"
# retain standing markers
grep -q "VERA_DEMO_SHOP_ONEWAV_20260905" "$CS" || fail "missing ONEWAV retention (MUSTBOOK ship)"
grep -q "VERA_DEMO_SHOP_NORMALIZE_20260904" "$CS" || fail "missing NORMALIZE retention (MUSTBOOK ship)"
grep -q "VERA_DEMO_SHOP_TTS_PREP_20260904" "$CS" || fail "missing TTS_PREP retention (MUSTBOOK ship)"
grep -q "VERA_DEMO_SHOP_NO_QR_LOOP_20260904" "$CS" || fail "missing NO_QR_LOOP retention (MUSTBOOK ship)"
grep -q "VERA_DEMO_SHOP_HARDEN_20260904" "$CS" || fail "missing HARDEN retention (MUSTBOOK ship)"
# VERA_DEMO_SHOP_NO_REGREET_20260906 + VERA_DEMO_SHOP_BARGE_SUSTAIN_20260906
grep -q "VERA_DEMO_SHOP_NO_REGREET_20260906" "$CS" || fail "missing Demo Shop NO_REGREET marker"
grep -q "maybeRewriteDemoShopRegreet" "$CS" || fail "missing maybeRewriteDemoShopRegreet"
grep -q "demo_shop_regreet_stripped" "$CS" || fail "missing regreet strip log"
grep -q "VERA_DEMO_SHOP_BARGE_SUSTAIN_20260906" "$CS" || fail "missing Demo Shop BARGE_SUSTAIN marker"
grep -q "listening_arm_blocked_playback_active" "$CS" || fail "missing listen-arm-while-playback block"
grep -q "stt_barge_in_ignored_unsustained" "$CS" || fail "missing unsustained barge ignore"
grep -q "demo_shop_barge_blip_discarded" "$CS" || fail "missing barge-blip discard"
grep -q "shouldDiscardDemoShopBargeBlip" "$CS" || fail "missing barge-blip helper"
grep -q "allowBrainStream" "$CS" || fail "missing Demo Shop STREAMTTS shopPlaybook exception"
grep -q "demo_shop_streamtts_blocked" "$CS" || fail "missing STREAMTTS blocked log"
grep -q "VERA_DEMO_SHOP_STREAMTTS_REMAINDER_20260906" "$CS" || fail "missing STREAMTTS remainder marker"
grep -q "extractDemoShopStreamRemainder" "$CS" || fail "missing extractDemoShopStreamRemainder"
grep -q "demo_shop_segment_remainder_queued" "$CS" || fail "missing remainder queued log"
grep -q "demo_shop_segment_remainder_spoken" "$CS" || fail "missing remainder spoken log"
grep -q "queueDemoShopStreamRemainder" "$CS" || fail "missing remainder queue helper"
grep -q "VERA_DEMO_SHOP_STREAMTTS_REMAINDER_DEDUP_20260906" "$CS" || fail "missing STREAMTTS remainder DEDUP marker"
grep -q "pickDemoShopStreamRemainder" "$CS" || fail "missing pickDemoShopStreamRemainder"
grep -q "demo_shop_segment_remainder_skipped_duplicate" "$CS" || fail "missing remainder skipped_duplicate log"
grep -q "mapDemoShopSpeakCursorAfterUnwrap" "$CS" || fail "missing unwrap cursor remap"
grep -q "VERA_DEMO_SHOP_PICKUP_HISTORY_20260906" "$CS" || fail "missing PICKUP_HISTORY marker"
grep -q "recordPickupGreetingInHistory" "$CS" || fail "missing pickup history inject"
grep -q "demo_shop_pickup_history_injected" "$CS" || fail "missing pickup inject log"
grep -q "maybeRewriteDemoShopPickupReopen" "$CS" || fail "missing pickup reopen strip"
grep -q "VERA_DEMO_SHOP_PLAYSERIAL_20260907" "$CS" || fail "missing PLAYSERIAL marker"
grep -q "demoShopPlayEpoch" "$CS" || fail "missing play epoch"
grep -q "audio_invariant_report" "$CS" || fail "missing audio invariant hangup report"
grep -q "VERA_DEMO_SHOP_AUDIOINV_20260907" "$CS" || fail "missing AUDIOINV marker on callSession"
grep -q "ensureAudioInvariantReport" "$CS" || fail "missing ensureAudioInvariantReport"
grep -q "VERA_DEMO_SHOP_BOOKCONFIRM_20260907" "$CS" || fail "missing BOOKCONFIRM marker"
grep -q "VERA_DEMO_SHOP_SLOTCARD_20260907" "$CS" || fail "missing SLOTCARD marker"
grep -q "buildTalkerBoardText" "$CS" || fail "missing buildTalkerBoardText"
grep -q "Call board" "$CS" || fail "missing Call board inject"
TB="$ROOT/patches/talkerBoard.js"
[[ -f "$TB" ]] || fail "missing talkerBoard patch"
grep -q "VERA_DEMO_SHOP_SLOTCARD_20260907" "$TB" || fail "missing SLOTCARD marker on talkerBoard"
grep -q "buildDemoShopTalkerBoard" "$TB" || fail "missing buildDemoShopTalkerBoard"
grep -q "talkerBoard.js:/app/veralux-voice-runtime/dist/calls/talkerBoard.js" "$ROOT/docker-compose.demo-tts.yml" || fail "missing talkerBoard compose mount"
grep -q "VERA_DEMO_SHOP_LISTENOPEN_20260907" "$CS" || fail "missing LISTENOPEN marker on callSession"
STT="$ROOT/patches/chunkedSTT.js"
grep -q "VERA_DEMO_SHOP_LISTENOPEN_20260907" "$STT" || fail "missing LISTENOPEN marker on chunkedSTT"
grep -q "VERA_DEMO_SHOP_PERSONEND_20260907" "$STT" || fail "missing PERSONEND marker on chunkedSTT"
grep -q "demo_shop_max_utt_deferred" "$STT" || fail "missing max-utt defer (person endpoint)"
grep -q "VERA_DEMO_SHOP_BARGEKEEP_20260907" "$STT" || fail "missing BARGEKEEP marker on chunkedSTT"
grep -q "VERA_DEMO_SHOP_DUPLEX_20260907" "$STT" || fail "missing DUPLEX marker on chunkedSTT"
grep -q "VERA_DEMO_SHOP_DUPLEX_20260907" "$CS" || fail "missing DUPLEX marker on callSession"
grep -q "VERA_DEMO_SHOP_SLOTHEAR_20260907" "$CS" || fail "missing SLOTHEAR marker"
grep -q "extractDemoShopPhone" "$CS" || fail "missing extractDemoShopPhone"
grep -q "takeDemoShopSpokenNameFromText" "$CS" || fail "missing takeDemoShopSpokenNameFromText"
grep -q "VERA_DEMO_SHOP_DTMF_20260907" "$CS" || fail "missing DTMF marker on callSession"
grep -q "onDemoShopDtmf" "$CS" || fail "missing onDemoShopDtmf"
DTMF="$ROOT/patches/demoShopDtmf.js"
[[ -f "$DTMF" ]] || fail "missing demoShopDtmf patch"
grep -q "VERA_DEMO_SHOP_DTMF_20260907" "$DTMF" || fail "missing DTMF marker on demoShopDtmf"
grep -q "ingestDemoShopDtmfDigit" "$DTMF" || fail "missing ingestDemoShopDtmfDigit"
grep -q "demoShopDtmf.js:/app/veralux-voice-runtime/dist/calls/demoShopDtmf.js" "$ROOT/docker-compose.demo-tts.yml" || fail "missing demoShopDtmf compose mount"
grep -q "sessionManager.js:/app/veralux-voice-runtime/dist/calls/sessionManager.js" "$ROOT/docker-compose.demo-tts.yml" || fail "missing sessionManager compose mount"
grep -q "telnyxWebhook.js:/app/veralux-voice-runtime/dist/routes/telnyxWebhook.js" "$ROOT/docker-compose.demo-tts.yml" || fail "missing telnyxWebhook compose mount"
grep -q "call.dtmf.received" "$ROOT/patches/telnyxWebhook.js" || fail "missing call.dtmf.received handler"
grep -q "onDtmfReceived" "$ROOT/patches/sessionManager.js" || fail "missing onDtmfReceived"
grep -q "keypad" "$TB" || fail "missing keypad on talkerBoard contact NEXT"
INV="$ROOT/patches/audioInvariantReport.js"
[[ -f "$INV" ]] || fail "missing audioInvariantReport patch"
grep -q "VERA_DEMO_SHOP_AUDIOINV_20260907" "$INV" || fail "missing AUDIOINV marker"
MI="$ROOT/patches/mediaIngest.js"
[[ -f "$MI" ]] || fail "missing mediaIngest observe-only patch"
grep -q "VERA_DEMO_SHOP_AUDIOINV_20260907" "$MI" || fail "missing AUDIOINV marker on mediaIngest"
grep -q "recordDecodeFailure" "$MI" || fail "missing decode-failure classify hook"
QS="$ROOT/patches/callQualitySummary.js"
[[ -f "$QS" ]] || fail "missing callQualitySummary patch"
grep -q "audioInvariants" "$QS" || fail "missing audioInvariants on quality summary"
grep -q "VERA_DEMO_SHOP_QWEN3_STREAM_20260908" "$CS" || fail "missing Qwen3 stream playTtsSegment marker"
grep -q "playQwen3StreamedSegment" "$CS" || fail "missing playQwen3StreamedSegment"
grep -q "qwen3Tts.js:/app/veralux-voice-runtime/dist/tts/qwen3Tts.js" "$ROOT/docker-compose.demo-tts.yml" || fail "missing qwen3Tts compose mount"
QW3="$ROOT/patches/qwen3Tts.js"
[[ -f "$QW3" ]] || fail "missing qwen3Tts patch"
grep -q "VERA_DEMO_SHOP_QWEN3_STREAM_20260908" "$QW3" || fail "missing Qwen3 stream client marker"
grep -q "magpieTts.js:/app/veralux-voice-runtime/dist/tts/magpieTts.js" "$ROOT/docker-compose.demo-tts.yml" || fail "missing magpieTts compose mount"
grep -q "meloTts.js:/app/veralux-voice-runtime/dist/tts/meloTts.js" "$ROOT/docker-compose.demo-tts.yml" || fail "missing meloTts compose mount"
grep -q "VERA_DEMO_SHOP_MAGPIE_MELO_20260908" "$ROOT/patches/DEMO-SHOP-FIX-LEDGER.md" || fail "missing Magpie/Melo ledger marker"
# Call Board extract lives in source; audio bind mounts stay until feel-pass image bake.
grep -q "export function planReceptionistTurn" "$ROOT/shared/src/callBoard.ts" || fail "missing planReceptionistTurn in shared Call Board"
grep -q "planDeskTurn" "$ROOT/veralux-voice-runtime/src/calls/callSession.ts" || fail "missing planDeskTurn in callSession source"
grep -q "intakeProfile" "$ROOT/shared/src/runtimeContract.ts" || fail "missing intakeProfile on runtime contract"
grep -q "await this.cidLookupPromise" "$ROOT/veralux-voice-runtime/src/calls/callSession.ts" || fail "missing CID await before greet/board"
grep -q "maybeRewriteDemoShopHandoff" "$CS" || fail "missing Demo Shop handoff rewrite"
if ! grep -q "transfersOn" "$CS"; then
  fail "MUSTBOOK handoff rewrite must no-op when transfers are on"
fi
echo "assert-demo-runtime-patches: OK"
