/** @type {import('tailwindcss').Config} */
module.exports = {
  blocklist: ["overline"],
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        serif: ["var(--vl-font-serif)"],
        sans: ["var(--vl-font-sans)"],
        mono: ["var(--vl-font-mono)"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        card: "var(--vl-radius-card)",
        input: "var(--vl-radius-input)",
      },
      boxShadow: {
        xs: "var(--vl-shadow-xs)",
        vl: "var(--vl-shadow-sm)",
      },
      colors: {
        vl: {
          canvas: "var(--vl-canvas)",
          warm: "var(--vl-canvas-warm)",
          surface: "var(--vl-surface)",
          soft: "var(--vl-surface-soft)",
          border: "var(--vl-border)",
          "border-strong": "var(--vl-border-strong)",
          text: "var(--vl-text)",
          secondary: "var(--vl-text-secondary)",
          muted: "var(--vl-text-muted)",
          "gold-soft": "var(--vl-gold-soft)",
          "gold-light": "var(--vl-gold-light)",
          gold: "var(--vl-gold)",
          "gold-deep": "var(--vl-gold-deep)",
          bronze: "var(--vl-bronze)",
          "success-bg": "var(--vl-success-bg)",
          success: "var(--vl-success)",
          "warning-bg": "var(--vl-warning-bg)",
          warning: "var(--vl-warning)",
          "danger-bg": "var(--vl-danger-bg)",
          danger: "var(--vl-danger)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "vl-fade-up": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "vl-fade-up": "vl-fade-up 240ms cubic-bezier(0.2, 0.8, 0.2, 1) both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
